on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/postgresql@v1
      with:
        connection-string: ${{ secrets.NASC_DELETE_CLI16_DEPLOY_TEST1_POSTGRESQL_CONNECTION_STRING
          }}
        plsql-file: .github\workflows\create_database_and_table.sql
        server-name: nasc-delete-cli16.postgres.database.azure.com
